"""Semi-transparent blue title washes and sub-label bands (no stroke frame).

A 1 px ``cv2.rectangle`` border around each ``*_title`` bbox drew a **bottom edge**
that sat between the column-header row and the first data row — reading as an
interior table divider.  Structural blue is meant to read as **outer** shells;
fills alone keep captions visible without bisecting the grid.

When ``colhdr_*`` rings parent to this ``*_title``, the title bbox can still span
the **column-header row** (TEST_3 MATV schedule: DESCRIPTION / MANUFACTURER / …).
We clip the wash to just above the first **multi-ring** ``colhdr_*`` row so that
row is not tinted — one-cell section titles (SPLITTERS, CONNECTORS, …) stay
filled; only the per-column label row is excluded.  Uses ``colhdr_*`` geometry
only (no cyan draw dependency).

``colhdr_*`` often parents to a **sibling** ``v2_sec0_title`` while the contour
synthesized a **thin** ``v2_sec1_title`` band that actually covers the same
column-header row — without resolving that link the thin band was fully washed.
"""

from __future__ import annotations

from typing import Any, Callable

import cv2

from .colors_bgr import BLUE, SUBHDR
from .style import DEFAULT_STYLE


def _colhdr_tied_to_title_band(
        tb: Any,
        h: Any,
        synth_by_id: dict[str, Any] | None,
) -> bool:
    """True when ``colhdr_*`` belongs to this title row or a sibling title shell.

    Column-header rings usually parent to ``v2_sec0_title`` while a neighbouring
    synthetic ``v2_sec1_title`` strip shares the same pixels — ``parent in
    (bid, wrap_id)`` alone misses the association.
    """
    bid = getattr(tb, "box_id", None) or ""
    wrap_id = getattr(tb, "parent_box_id", None)
    pid = getattr(h, "parent_box_id", None)
    if pid in (bid, wrap_id):
        return True
    if not synth_by_id or not wrap_id or not pid:
        return False
    parent = synth_by_id.get(pid)
    if parent is None:
        return False
    if getattr(parent, "parent_box_id", None) != wrap_id:
        return False
    pkey = getattr(parent, "box_id", "") or ""
    if not (pkey.endswith("_title") or pkey.endswith("_sublabel")):
        return False
    hy0 = int(h.px_bbox[1])
    ty0, ty1 = int(tb.px_bbox[1]), int(tb.px_bbox[3])
    if hy0 < ty0 - 10 or hy0 > ty1 + 12:
        return False
    return True


def _has_substantial_body_below(
    tb: Any,
    box_by_id: dict[str, Any] | None,
) -> bool:
    """True when the title's parent wrapper extends well below the title.

    The earlier ``bw <= 200 and bh <= 40 → skip`` rule was tuned to drop
    revision-sidebar splinters — bogus narrow ``_title`` boxes generated by
    text-section detection inside narrow tables.  Real narrow titles (e.g.
    ``v3_title`` for the ABBREVIATIONS column on test5) share the same size
    profile but sit on top of a tall labelled section with a substantial
    body below.  Splinters do not.

    We look up the title's parent wrapper.  ``box_by_id`` must contain
    BOTH synthetic and regular (non-synthetic) boxes — the parent is
    typically a regular contour wrapper like ``v3``, not a synthetic.
    If the wrapper's bottom is at least ``min_body_h`` px below the
    title's bottom, the section has a real body — the title is genuine.
    Returning True overrides the skip.
    """
    if box_by_id is None:
        return False
    bid = getattr(tb, "box_id", "") or ""
    if not bid.endswith("_title"):
        return False
    pid = getattr(tb, "parent_box_id", None)
    parent = box_by_id.get(pid) if pid else None
    if parent is None:
        # fall back to id-suffix derivation
        wrap_id = bid[: -len("_title")]
        parent = box_by_id.get(wrap_id)
    if parent is None:
        return False
    p_y1 = int(parent.px_bbox[3])
    t_y1 = int(tb.px_bbox[3])
    # Body must extend at least 60 px below the title to count as a real
    # labelled section.  Splinter "titles" inside narrow tables typically
    # have a parent ending within a few px of the title's own bottom.
    return (p_y1 - t_y1) >= 60


def _skip_title_alpha(tb: Any, box_by_id: dict[str, Any] | None = None) -> bool:
    """Skip wash only for **non–text-section** narrow strips (revision / sidebar).

    ``textsec_*_title`` bands are intentionally **word-tight** (often ``w`` ≈
    100–190 px) so they still need the blue wash (test5 schedule captions).
    The old ``bw <= 200`` gate treated every font-detected caption as a "narrow
    sidebar" and skipped the fill entirely.

    ``tbstruct_*_title`` bands are intentionally **cell-shaped** — for tall
    project-name cells holding rotated multi-line text, ``bh`` is regularly
    ≥ 200 px and ``bw`` is the full cell width (~120 px on test5).  The old
    ``bh > 34 and bw > 120`` body-band gate would skip them.  Exempt them
    explicitly so the title wash renders.

    ``tbcell_*_title`` bands are the table-title row of a tabular cluster
    (e.g. "REVISION SCHEDULE" above the column-header strip).  They are
    short and narrow (bw ≈ 120, bh ≈ 22) — exactly the size profile the
    earlier ``bw <= 200 and bh <= 40 → skip`` rule was tuned to drop as
    revision-sidebar splinters.  Exempt them so the wash renders, since
    the cellular-title pass has already verified the title pattern.

    For other narrow titles (e.g. ``v3_title`` on the ABBREVIATIONS column),
    a structural parent-body check distinguishes real from splinter: a real
    titled section has a parent BLUE wrapper extending substantially below
    the title's bottom (the body of the section); a splinter doesn't.
    """
    bid = getattr(tb, "box_id", "") or ""
    if bid.startswith("textsec_"):
        return False
    if bid.startswith("tbstruct_") and bid.endswith("_title"):
        return False
    if bid.startswith("tbcell_") and bid.endswith("_title"):
        return False
    x0, y0, x1, y1 = tb.px_bbox
    bw = x1 - x0
    bh = y1 - y0
    if bh > 50 and bw > 120:
        return True
    if bw <= 200 and bh <= 40:
        # Possibly a sidebar splinter — but a real narrow title has a tall
        # parent body extending below it.  Check before skipping.
        if _has_substantial_body_below(tb, box_by_id):
            return False
        return True
    return False


def _colhdr_row_clip_top_y(
        tb: Any,
        colhdr_boxes: list[Any],
        *,
        y_slack_below: int = 16,
        synth_by_id: dict[str, Any] | None = None,
) -> int | None:
    """Return min(colhdr top) for a **multi-ring** header row tied to this title.

    ``None`` means caller keeps the synthetic title bottom ``y1``.
    """
    x0, y0, x1, y1 = tb.px_bbox
    bid = getattr(tb, "box_id", None)
    wrap_id = getattr(tb, "parent_box_id", None)
    bw = x1 - x0
    tops_x: list[tuple[int, int, int]] = []  # (hy0, hx0, hx1)
    y_hi = y1 + int(y_slack_below)
    for h in colhdr_boxes:
        if not _colhdr_tied_to_title_band(tb, h, synth_by_id):
            continue
        hx0, hy0, hx1, hy1 = (int(v) for v in h.px_bbox)
        if hy0 < y0 - 2 or hy0 > y_hi:
            continue
        tops_x.append((hy0, hx0, hx1))
    if len(tops_x) < 2:
        return None
    # Same baseline cluster (column headers share one row)
    min_y = min(t[0] for t in tops_x)
    row = [t for t in tops_x if t[0] <= min_y + 4]
    if len(row) < 2:
        return None
    span = max(t[2] for t in row) - min(t[1] for t in row)
    if span < int(0.28 * max(1, bw)):
        return None
    return min(t[0] for t in row)


def draw_title_band_highlights(
        canvas: Any,
        *,
        main_bands: list[Any],
        sub_bands: list[Any],
        title_bands: list[Any],
        colhdr_boxes: list[Any],
        textsec_splinter_inside_narrow_table: Callable[[Any], bool],
        synth_by_id: dict[str, Any] | None = None,
        box_by_id: dict[str, Any] | None = None,
) -> None:
    """Pass 2: alpha title fills only (no rectangle stroke inside the table).

    ``box_by_id`` is a complete index of all boxes (synthetic + regular) used
    by the title-skip gate to look up the parent wrapper of a candidate
    title.  Distinguishes real narrow titles (parent has a substantial body
    below) from sidebar splinters.  When None, the gate falls back to its
    the earlier size-only heuristic.
    """
    if main_bands:
        overlay = canvas.copy()
        # Track which bands need the sub-header style (different color)
        # rather than the regular blue title wash.  A sub-header is a
        # title that's nested inside a SECTION X.Y parent (Rule 12).
        subheader_bands: list = []
        for tb in main_bands:
            if _skip_title_alpha(tb, box_by_id):
                continue
            # Sub-headers handled in a separate pass with SUBHDR colour.
            if getattr(tb, "is_subheader", False):
                subheader_bands.append(tb)
                continue
            x0, y0, x1, y1 = tb.px_bbox
            bid = getattr(tb, "box_id", None)
            wrap_id = getattr(tb, "parent_box_id", None)
            # ``colhdr_*`` usually parents to ``textsec_*_title`` (test5) **or** to the
            # contour wrapper ``v8`` while the title band is ``v8_sec0_title`` (TEST_3
            # MATV).  Only the former matched before, so the wash never clipped.
            hdr_tops: list[int] = []
            for h in colhdr_boxes:
                if not _colhdr_tied_to_title_band(tb, h, synth_by_id):
                    continue
                hy0 = int(h.px_bbox[1])
                # Header rings that sit **inside** this title bbox's vertical span
                # (not body rows farther down the same wrapper).
                if y0 <= hy0 < y1:
                    hdr_tops.append(hy0)
            row_clip_y0 = _colhdr_row_clip_top_y(
                tb, colhdr_boxes, synth_by_id=synth_by_id)
            if row_clip_y0 is not None:
                # Multi-column header row (≥2 ``colhdr_*`` on one baseline): never
                # paint into that band even when ``hy0 == y1`` or slightly below bbox.
                alt_end = row_clip_y0 - 2
                if hdr_tops:
                    y_fill_end = min(min(hdr_tops) - 2, alt_end)
                else:
                    y_fill_end = alt_end
                if y_fill_end < y0 + 6:
                    continue
                y1 = y_fill_end
            elif hdr_tops:
                y_fill_end = min(hdr_tops) - 2
                if y_fill_end < y0 + 6:
                    continue
                y1 = y_fill_end
            cv2.rectangle(overlay, (x0, y0), (x1, y1), BLUE, cv2.FILLED)
        cv2.addWeighted(overlay, DEFAULT_STYLE.title_alpha, canvas, 1.0 - DEFAULT_STYLE.title_alpha, 0, canvas)

        # Sub-header pass: nested ``SECTION X.Y`` child titles render
        # with the SUBHDR (green) wash so they read as sub-headings,
        # not peer titles.  The wash is widened to the corresponding
        # ``_body`` width so each sub-section reads as a single
        # full-width unit (otherwise the green band only covers the
        # title text and the section visually splits between label
        # column and value column).  If no body exists (sub-header
        # inside a continuation block), widen to the enclosing
        # continuation's width instead.
        if subheader_bands:
            # Build continuation-block bbox lookup once.
            continuation_bboxes = []
            if synth_by_id is not None:
                continuation_bboxes = [
                    b.px_bbox for b in synth_by_id.values()
                    if str(getattr(b, "box_id", "")).endswith("_continuation")
                ]
            overlay2 = canvas.copy()
            for tb in subheader_bands:
                x0, y0, x1, y1 = tb.px_bbox
                bid = getattr(tb, "box_id", "") or ""
                widened = False
                if bid.endswith("_title") and synth_by_id is not None:
                    body_id = bid[:-len("_title")] + "_body"
                    body = synth_by_id.get(body_id)
                    if body is not None:
                        bx0, _by0, bx1, _by1 = body.px_bbox
                        x0 = min(x0, bx0)
                        x1 = max(x1, bx1)
                        widened = True
                # Fallback: widen to enclosing continuation block
                # when no body exists.
                if not widened:
                    cy = 0.5 * (y0 + y1)
                    cx = 0.5 * (x0 + x1)
                    for cb_bbox in continuation_bboxes:
                        cbx0, cby0, cbx1, cby1 = cb_bbox
                        if (cbx0 <= cx <= cbx1
                                and cby0 <= cy <= cby1):
                            x0 = min(x0, cbx0)
                            x1 = max(x1, cbx1)
                            break
                cv2.rectangle(overlay2, (x0, y0), (x1, y1), SUBHDR, cv2.FILLED)
            cv2.addWeighted(overlay2, DEFAULT_STYLE.title_alpha, canvas, 1.0 - DEFAULT_STYLE.title_alpha, 0, canvas)
    if sub_bands:
        overlay = canvas.copy()
        for tb in sub_bands:
            if textsec_splinter_inside_narrow_table(tb):
                continue
            x0, y0, x1, y1 = tb.px_bbox
            cv2.rectangle(overlay, (x0, y0), (x1, y1), BLUE, cv2.FILLED)
        cv2.addWeighted(overlay, DEFAULT_STYLE.sublabel_alpha, canvas, 1.0 - DEFAULT_STYLE.sublabel_alpha, 0, canvas)
